config/routes.rb
Rails.application.routes.draw do
  resources :anagram_compares

  get 'welcome/index'

  root 'welcome#index'

end

app/models/anagram_compare.rb
class AnagramCompare < ActiveRecord::Base

	before_save :is_anagram

	def is_anagram
  		self.status = self.clean(original) == self.clean(wannabe)
  		self.status != nil
  	end
  	
  	def clean(string)
		string.gsub(/\s+/, "").mb_chars.downcase.to_s.chars.sort{ |a, b| a.casecmp(b) }.join
	end
end

app/controllers/anagram_compares_controller.rb
class AnagramComparesController < ApplicationController
  before_action :set_anagram_compare, only: [:show, :edit, :update, :destroy]

  # GET /anagram_compares
  # GET /anagram_compares.json
  def index
    @anagram_compares = AnagramCompare.all
  end

  # GET /anagram_compares/1
  # GET /anagram_compares/1.json
  def show
  end

  # GET /anagram_compares/new
  def new
    @anagram_compare = AnagramCompare.new
  end

  # Redirect to index to block users from editing
  # GET /anagram_compares/1/edit
  def edit
    redirect_to action: 'index', status: 303
  end

  # POST /anagram_compares
  # POST /anagram_compares.json
  def create

    @anagram_compare = AnagramCompare.new(anagram_compare_params)

    respond_to do |format|
      if @anagram_compare.save
        format.html { redirect_to @anagram_compare, notice: 'Anagram compare was successfully created.' }
        format.json { render :show, status: :created, location: @anagram_compare }
      else
        format.html { render :new }
        format.json { render json: @anagram_compare.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /anagram_compares/1
  # PATCH/PUT /anagram_compares/1.json
  def update
    respond_to do |format|
      if @anagram_compare.update(anagram_compare_params)
        format.html { redirect_to @anagram_compare, notice: 'Anagram compare was successfully updated.' }
        format.json { render :show, status: :ok, location: @anagram_compare }
      else
        format.html { render :edit }
        format.json { render json: @anagram_compare.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /anagram_compares/1
  # DELETE /anagram_compares/1.json
  def destroy
    @anagram_compare.destroy
    respond_to do |format|
      format.html { redirect_to anagram_compares_url, notice: 'Anagram compare was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_anagram_compare
      @anagram_compare = AnagramCompare.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def anagram_compare_params
      params.require(:anagram_compare).permit(:original, :wannabe, :status)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/anagram_compares_helper.rb
module AnagramComparesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/anagram_compares/_form.html.erb
<%= simple_form_for(@anagram_compare) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :original, label: 'Put original string here...' %>
    <%= f.input :wannabe, label: 'Put the string you wanna compare here...' %>
    </br>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/anagram_compares/edit.html.erb
<h1>Editing anagram_compare</h1>

<%= render 'form' %>

<%= link_to 'Show', @anagram_compare %> |
<%= link_to 'Back', anagram_compares_path %>

app/views/anagram_compares/index.html.erb
<div class="jumbotron" style="background-image: url(<%= asset_path 'dubrovink.png' %>)">
  <div class="container">
    <h1 style="color: white; text-shadow: 3px 3px 3px black;">Detect if is an anagram!!</h1>
    <p style="color: white; text-shadow: 3px 3px 3px black;">A Eradicating Fast Men!!</p>
    <p><a href="http://github.com/rafaelescrich/anagram-rd" target="_blank" class="btn btn-primary btn-lg">Github Code</a></p>
  </div>
  <div class="clear"></div>
</div>
<div class="container">
    <div class="col-sm-12">
          <!--panel-->
          <div class="panel panel-primary">
              <!-- Default panel contents -->
              <div class="panel-heading"><h4><strong>List of anagrams</strong></h4></div>
              <div class="panel-body">
                  <!--table-->
                  <table class="table table-condensed table-striped table-responsive">
                      <thead>
                          <tr>
                              <th class="text-left">Original</th>
                              <th class="text-center">Wannabe</th>
                              <th class="text-center">Status</th>
                              <th class="text-right">Actions</th>
                          </tr>
                      </thead>
                      <tbody>
                          <% @anagram_compares.each do |anagram_compare| %>
                          <tr>
                              <td class="text-left"><%= anagram_compare.original %></th>
                              <td class="text-center"><%= anagram_compare.wannabe %></th>
                              <td class="text-center"><span class="badge badge-info"><%= anagram_compare.status %></th>
                              <td class="text-right"><%= link_to 'Show', anagram_compare %></td>
                              <td class="text-right"><%= link_to 'Destroy', anagram_compare, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                          </tr>
                        <% end %>
                      </tbody>
                  </table>
                  <!--end of table-->
                  <%= link_to 'New Anagram compare', new_anagram_compare_path , :class => 'btn btn-success btn-lg btn-block pull-right' %>
              </div>
          </div>
          <!--end of panel-->
      </div>
    </div>

app/views/anagram_compares/new.html.erb
<div class="jumbotron" style="background-image: url(<%= asset_path 'dubrovink.png' %>)">
  <div class="container">
    <h1 style="color: white; text-shadow: 3px 3px 3px black;">Detect if is an anagram!!</h1>
    <p style="color: white; text-shadow: 3px 3px 3px black;">A Eradicating Fast Men!!</p>
    <p><a href="http://github.com/rafaelescrich/anagram-rd" target="_blank" class="btn btn-primary btn-lg">Github Code</a></p>
  </div>
  <div class="clear"></div>
</div>

<div class="container">
    <div class="col-sm-12">
          <!--panel-->
          <div class="panel panel-primary">
              <!-- Default panel contents -->
              <div class="panel-heading"><h4><strong>New anagram comparison</strong></h4></div>
              <div class="panel-body">
                  <!--table-->
                  <p class="table table-condensed table-striped table-responsive">
                      <%= render 'form' %>
                  </p>
				          <%= link_to 'Back', anagram_compares_path , :class => 'btn btn-danger btn-lg btn-block pull-right' %>
              </div>
          </div>
    </div>
</div>

app/views/anagram_compares/show.html.erb
<div class="jumbotron" style="background-image: url(<%= asset_path 'dubrovink.png' %>)">
  <div class="container">
    <h1 style="color: white; text-shadow: 3px 3px 3px black;">Detect if is an anagram!!</h1>
    <p style="color: white; text-shadow: 3px 3px 3px black;">A Eradicating Fast Men!!</p>
    <p><a href="http://github.com/rafaelescrich/anagram-rd" target="_blank" class="btn btn-primary btn-lg">Github Code</a></p>
  </div>
  <div class="clear"></div>
</div>

<div class="container">
    <div class="col-sm-12">
          <!--panel-->
          <div class="panel panel-primary">
              <!-- Default panel contents -->
              <div class="panel-heading"><h4><strong>Testing anagram</strong></h4></div>
              <div class="panel-body">
					<p id="notice"><%= notice %></p>

					<p>
					  <strong>Original:</strong>
					  <%= @anagram_compare.original %>
					</p>

					<p>
					  <strong>Wannabe:</strong>
					  <%= @anagram_compare.wannabe %>
					</p>

					<p>
					  <strong>Status:</strong>
					  <%= @anagram_compare.status %>
					</p>
					<%= link_to 'Back', anagram_compares_path, :class => 'btn btn-danger btn-lg btn-block pull-right' %>
              </div>
          </div>
          <!--end of panel-->
      </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Anagram</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<div class="jumbotron" style="background-image: url(<%= asset_path 'dubrovink.png' %>)">
  <div class="container">
    <h1 style="color: white; text-shadow: 3px 3px 3px black;">Detect if is an anagram!!</h1>
    <p style="color: white; text-shadow: 3px 3px 3px black;">A Eradicating Fast Men!!</p>
    <p><a href="http://github.com/rafaelescrich/anagram-rd" target="_blank" class="btn btn-primary btn-lg">Github Code</a></p>
  </div>
  <div class="clear"></div>
</div>
<div class="container">
  	<div class="col-lg-8 text-left">
  		<div class="panel panel-primary">
              <!-- Default panel contents -->
              <div class="panel-heading"><h4><b>List of anagrams</b></h4></div>
              <div class="panel-body">
	    			<h5><b>This aplicattion was written to demonstrate an anagram detector in ruby on rails with heroku deployment. I used Twitter Bootstrap to make things prettier and faster to code. The code is available in Github in the button ahead. Thanks.</b></h5>
	    			<p><a href="/anagram_compares" class="btn btn-success btn-lg pull-left">Go to app =></a></p>
	    	  </div>
	    	 </div>	
   </div>
   <div class="col-lg-6 text-left"></div>
</div>